### ISSUE TITLE
Memory leak in WCSimReader

### ISSUE THREAD

**Issue by ast0815** [HKDAQ/TriggerApplication#51]
When I run a tool chain with only the WCSimReader as active tool on a simulated supernova file, the memory footprint rises from ~100 MB to ~5 GB by the end of the file. When enabling also DataOut, ReconDataOut, and ReconReset are enabled it grows to double that, ~10 GB.

**Comment by tdealtry** [comment]
Closing this since a fix has been found for this initial issue, but #61 is still open
